spring.application.name=witchfirerandomizer
server.address=127.0.0.1
server.port=9090

# Development default: disable template caching so changes reflect immediately on page refresh
spring.thymeleaf.cache=false